### ISSUE TITLE
Bad colors for default Gvim colorscheme (white)

### ISSUE THREAD

**Issue by habamax** [Yggdroot/LeaderF#402]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 17 2019 23:02:10)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-2318
Compiled by appveyor@APPVYR-WIN
Huge version with GUI.  Features included (+) or not (-):
+acl                +comments           +file_in_path       +listcmds           +persistent_undo    -sun_workshop       +vertsplit
+arabic             +conceal            +find_in_path       +localmap           -postscript         +syntax             +virtualedit
+autocmd            +cryptv             +float              +lua/dyn            +printer            +tag_binary         +visual
+autochdir          +cscope             +folding            +menu               +profile            -tag_old_static     +visualextra
+autoservername     +cursorbind         -footer             +mksession          +python/dyn         -tag_any_white      +viminfo
+balloon_eval       +cursorshape        +gettext/dyn        +modify_fname       +python3/dyn        +tcl/dyn            +vreplace
-balloon_eval_term  +dialog_con_gui     -hangul_input       +mouse              +quickfix           -termguicolors      -vtp
+browse             +diff               +iconv/dyn          +mouseshape         +reltime            +terminal           +wildignore
++builtin_terms     +digraphs           +insert_expand      +multi_byte_ime/dyn +rightleft          -termresponse       +wildmenu
+byte_offset        +directx            +job                +multi_lang         +ruby/dyn           +textobjects        +windows
+channel            -dnd                +jumplist           +mzscheme/dyn       +scrollbind         +textprop           +writebackup
+cindent            -ebcdic             +keymap             +netbeans_intg      +signs              -tgetent            -xfontset
+clientserver       +emacs_tags         +lambda             +num64              +smartindent        +timers             -xim
+clipboard          +eval               +langmap            +ole                +sound              +title              +xpm_w32
+cmdline_compl      +ex_extra           +libcall            +packages           +spell              +toolbar            -xterm_save
+cmdline_hist       +extra_search       +linebreak          +path_extra         +startuptime        +user_commands      
+cmdline_info       -farsi              +lispindent         +perl/dyn           +statusline         +vartabs            
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL   -DFEAT_XPM_W32   -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG  /Zl /MT -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_GUI_MSWIN -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86t.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python37.dll\" -DFEAT_MZSCHEME -I "C:\Program Files\Racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_a36fs8.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_a36fs8.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl528.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=24 -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby240.dll\" -DFEAT_HUGE /Fd.\ObjGXOULYHTRZAMD64/ /Zi
Linking: link  /nologo /opt:ref /LTCG:STATUS /HIGHENTROPYVA:NO oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib /machine:AMD64 gdi32.lib version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib netapi32.lib  /machine:AMD64  libcmt.lib oleaut32.lib user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python37.lib   "C:\Tcl\lib\tclstub86.lib" winmm.lib WSock32.lib xpm\x64\lib-vc14\libXpm.lib /PDB:gvim.pdb -debug

```

- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): python27.dll
- Output of `:echo &pythonthreedll`(only vim, not neovim): python37.dll
- Output of `:py print(sys.version)`:
```
Error detected while processing function EvalVim:
line   31:
E370: Could not load library python27.dll
Error detected while processing function EvalVim:
line   31:
E263: Sorry, this command is disabled, the Python library could not be loaded.
``` 
- Output of `:py3 print(sys.version)`: `3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]` 
- Output of `:echo g:Lf_Debug_Cmd`: `rg --no-messages --files   -g "!.svn" -g "!.git" -g "!.hg" -g "!*.sw?" -g "!~$*" -g "!*.bak" -g "!*.exe" -g "!*.o" -g "!*.so" -g "!*.py[co]" -g "!*.tmp" -g "!*.ttf" -L --hidden` 
- Output of `:echo g:Lf_FilesFromCache`:  0
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
	let g:Lf_WindowPosition = 'popup'
	let g:Lf_StlSeparator = { 'left': '', 'right': '' }
	let g:Lf_ShortcutF = '<leader>ff'
	let g:Lf_Shortcutb = '<leader>b'
	let g:Lf_WindowHeight = 0.30
	let g:Lf_ShowHidden = 1
	let g:Lf_FollowLinks = 1
	let g:Lf_NormalMap = {"File":   [["u", ':LeaderfFile ..<CR>']]}
    let g:Lf_PreviewResult = { 'BufTag': 0 }
    let g:Lf_WildIgnore = {
            \ 'dir': ['.svn','.git','.hg'],
            \ 'file': ['*.sw?','~$*','*.bak','*.exe','*.o','*.so','*.py[co]', '*.tmp','*.ttf']
            \}
    let g:Lf_MruWildIgnore = copy(g:Lf_WildIgnore)
	let g:Lf_UseVersionControlTool = 0
	nnoremap <leader>f/ :Leaderf rg 
	nnoremap <leader>/ :LeaderfLine<CR>
	nnoremap <leader>f; :LeaderfHistoryCmd<CR>
	nnoremap <leader>ftt :LeaderfTag<CR>
	nnoremap <leader>ftb :LeaderfBufTag<CR>
	nnoremap <leader>fh :LeaderfHelp<CR>
	nnoremap <leader>fm :LeaderfMru<CR>
	nnoremap <leader>fs :LeaderfSelf<CR>
	nnoremap <leader>fc :LeaderfColorscheme<CR>
	nnoremap <leader>fdd :LeaderfFile ~/docs<CR>
	packadd LeaderF
```

### Describe your question, feature request, or bug.
default colors are subjectively bad

### Steps to reproduce
Open GVim with default light colorscheme and run leaderf in popup

### Actual behaviour
![image](https://user-images.githubusercontent.com/234774/69222729-1cd06300-0b8b-11ea-9666-2097f66a4686.png)

![image](https://user-images.githubusercontent.com/234774/69222748-25c13480-0b8b-11ea-9881-42b8bce74176.png)

If you manually `set background=dark` then it looks ok:
![image](https://user-images.githubusercontent.com/234774/69222837-51dcb580-0b8b-11ea-923a-24f5720ebd0c.png)

But the rest of vim syntax highlighting becomes unreadable.

**Comment by habamax** [comment]
It is actually bad for probably all light colorschemes:

solarized (with bg=light):

![image](https://user-images.githubusercontent.com/234774/69223051-ad0ea800-0b8b-11ea-9f7e-0eaf2b072fe2.png)

gruvbox
![image](https://user-images.githubusercontent.com/234774/69223102-bf88e180-0b8b-11ea-9502-4fc39fe46bf6.png)

**Comment by Yggdroot** [comment]
Yes, Leaderf need a default light colorscheme.

**Comment by habamax** [comment]
I have tried to change background color of popup window from within my colorscheme:

```
hi Lf_hl_popup_window guibg=#eaeaea guifg=#505050 ctermbg=254 ctermfg=239
```
And it looks like it is overwritten by internal plugin logic.

If I execute it afterwards popup background is changed.

PS, what I try to do is to define "proper" colors in my colorschemes (not the ones leaderf provides in autoloads/colorscheme) and for now it looks like:

```
"" LeaderF
" separators have an issue -- they are changed by LeaderF
let s:leaderf_modes = [
			\'File', 'Buffer', 'Mru', 'Help', 'Rg', 
			\'Line', 'Tag', 'BufTag', 'Function', 'Cmd_History',
			\'Colorscheme', 'Self'
			\]
for lf_mode in s:leaderf_modes
	execute 'hi Lf_hl_'.lf_mode.'_stlName guibg=#3c3c3c guifg=#c0c0c0 gui=NONE ctermbg=237 ctermfg=250'
	execute 'hi Lf_hl_'.lf_mode.'_stlMode guibg=#3c3c3c guifg=#c0c0c0 gui=NONE ctermbg=237 ctermfg=250'
	execute 'hi Lf_hl_'.lf_mode.'_stlCategory guibg=#3c3c3c guifg=#c0c0c0 gui=NONE ctermbg=237 ctermfg=250'
	execute 'hi Lf_hl_'.lf_mode.'_stlCwd guibg=#3c3c3c guifg=#ffffff gui=NONE ctermbg=237 ctermfg=15'
	execute 'hi Lf_hl_'.lf_mode.'_stlSeparator0 guibg=#3c3c3c guifg=#c0c0c0 gui=NONE ctermbg=237 ctermfg=250'
	execute 'hi Lf_hl_'.lf_mode.'_stlSeparator1 guibg=#3c3c3c guifg=#c0c0c0 gui=NONE ctermbg=237 ctermfg=250'
	execute 'hi Lf_hl_'.lf_mode.'_stlSeparator2 guibg=#3c3c3c guifg=#c0c0c0 gui=NONE ctermbg=237 ctermfg=250'
	execute 'hi Lf_hl_'.lf_mode.'_stlSeparator3 guibg=#3c3c3c guifg=#c0c0c0 gui=NONE ctermbg=237 ctermfg=250'
	execute 'hi Lf_hl_'.lf_mode.'_stlSeparator4 guibg=#3c3c3c guifg=#c0c0c0 gui=NONE ctermbg=237 ctermfg=250'
	execute 'hi Lf_hl_'.lf_mode.'_stlSeparator5 guibg=#3c3c3c guifg=#c0c0c0 gui=NONE ctermbg=237 ctermfg=250'
	execute 'hi Lf_hl_'.lf_mode.'_stlLineInfo guibg=#3c3c3c guifg=#ffffff gui=NONE ctermbg=237 ctermfg=250'
	execute 'hi Lf_hl_'.lf_mode.'_stlNameOnlyMode guibg=#3c3c3c guifg=#c0c0c0 gui=NONE ctermbg=237 ctermfg=250'
	execute 'hi Lf_hl_'.lf_mode.'_stlRegexMode guibg=#3c3c3c guifg=#c0c0c0 gui=NONE ctermbg=237 ctermfg=250'
	execute 'hi Lf_hl_'.lf_mode.'_stlFullPathMode guibg=#3c3c3c guifg=#c0c0c0 gui=NONE ctermbg=237 ctermfg=250'
	execute 'hi Lf_hl_'.lf_mode.'_stlFuzzyMode guibg=#3c3c3c guifg=#c0c0c0 gui=NONE ctermbg=237 ctermfg=250'
	execute 'hi Lf_hl_'.lf_mode.'_stlTotal guibg=#3c3c3c guifg=#ffffff gui=NONE ctermbg=237 ctermfg=15'
	execute 'hi Lf_hl_'.lf_mode.'_stlBlank guibg=#3c3c3c guifg=#ffffff gui=NONE ctermbg=237 ctermfg=15'
endfor

hi link Lf_hl_bufDirname Comment
hi link Lf_hl_funcDirname Comment
hi link Lf_hl_rgFilename Comment
hi link Lf_hl_rgTagFile Comment
hi Lf_hl_popup_window guibg=#eaeaea guifg=#505050 ctermbg=254 ctermfg=239
hi Lf_hl_cursorline guifg=#505050 ctermfg=16 
```

**Comment by habamax** [comment]
![vim-leaderf-highlight-issue1](https://user-images.githubusercontent.com/234774/69314986-95e0c080-0c46-11ea-92f3-f205be63ea7b.gif)

**Comment by habamax** [comment]
Could you also help me changing cursor line background properly?

![image](https://user-images.githubusercontent.com/234774/69315366-68484700-0c47-11ea-8cfc-d8227d340d4f.png)

**Comment by Yggdroot** [comment]
I'm fixing this issue, to provide a global dict like 
https://github.com/Yggdroot/LeaderF/blob/b3a242db70cc22b467f2394f5186a85ab8a1dbcc/doc/leaderf.txt#L236-L330

Now a colorscheme called `gruvbox_material` is available, you can set
`let g:Lf_PopupColorscheme = 'gruvbox_material' ` for light colorscheme.

**Comment by habamax** [comment]
> `let g:Lf_PopupColorscheme = 'gruvbox_material' ` for light colorscheme.

It looks good! Thx!

**Comment by habamax** [comment]
Is/would be there `g:Lf_PopupPalette` available?

**Comment by Yggdroot** [comment]
> Is/would be there `g:Lf_PopupPalette` available?

Still being implemented.

**Comment by habamax** [comment]
> 
> 
> I'm fixing this issue, to provide a global dict like
> 
> https://github.com/Yggdroot/LeaderF/blob/b3a242db70cc22b467f2394f5186a85ab8a1dbcc/doc/leaderf.txt#L236-L330

How do you refresh palette after it was changed in a colorscheme?

I have defined  `g:Lf_StlPalette` in 2 colorschemes and after colorscheme switch it doesn't change leaderf colors. Should I call some function to apply colors?

**Comment by Yggdroot** [comment]
It works as designed. 
You mean you defined the color of Leaderf in vim's colorscheme, it is supposed not to do so.

**Comment by habamax** [comment]
> It works as designed.
> You mean you defined the color of Leaderf in vim's colorscheme, it is supposed not to do so.

That is pity :(

So then my initial approach https://github.com/Yggdroot/LeaderF/issues/402#issuecomment-556948427 was kind of hack that actually works.


I have also tried (again in my colorscheme files).

```
let s:palette = { 
			\   'stlName': { 
			\       'gui': 'bold', 
			\       'font': 'NONE', 
			\       'guifg': '#9b9b9b', 
			\       'guibg': '#3c3c3c', 
			\       'cterm': 'NONE', 
			\       'ctermfg': '237',
			\       'ctermbg': '241' 
			\   }, 
			\   'stlCategory': { 
			\       'gui': 'NONE', 
			\       'font': 'NONE', 
			\       'guifg': '#9b9b9b', 
			\       'guibg': '#3c3c3c', 
			\       'cterm': 'NONE', 
			\       'ctermfg': '237',
			\       'ctermbg': '241' 
			\   }, 
			\   'stlNameOnlyMode': { 
			\       'gui': 'NONE', 
			\       'font': 'NONE', 
			\       'guifg': '#9b9b9b', 
			\       'guibg': '#3c3c3c', 
			\       'cterm': 'NONE', 
			\       'ctermfg': '237',
			\       'ctermbg': '241' 
			\   }, 
			\   'stlFullPathMode': { 
			\       'gui': 'NONE', 
			\       'font': 'NONE', 
			\       'guifg': '#9b9b9b', 
			\       'guibg': '#3c3c3c', 
			\       'cterm': 'NONE', 
			\       'ctermfg': '237',
			\       'ctermbg': '241' 
			\   }, 
			\   'stlFuzzyMode': { 
			\       'gui': 'NONE', 
			\       'font': 'NONE', 
			\       'guifg': '#9b9b9b', 
			\       'guibg': '#3c3c3c', 
			\       'cterm': 'NONE', 
			\       'ctermfg': '237',
			\       'ctermbg': '241' 
			\   }, 
			\   'stlRegexMode': { 
			\       'gui': 'NONE', 
			\       'font': 'NONE', 
			\       'guifg': '#9b9b9b', 
			\       'guibg': '#3c3c3c', 
			\       'cterm': 'NONE', 
			\       'ctermfg': '237',
			\       'ctermbg': '241' 
			\   }, 
			\   'stlCwd': { 
			\       'gui': 'NONE', 
			\       'font': 'NONE', 
			\       'guifg': '#d0d0d0', 
			\       'guibg': '#5c5c5c', 
			\       'cterm': 'NONE', 
			\       'ctermfg': '252', 
			\       'ctermbg': '241' 
			\   }, 
			\   'stlBlank': { 
			\       'gui': 'NONE', 
			\       'font': 'NONE', 
			\       'guifg': '#d0d0d0', 
			\       'guibg': '#5c5c5c', 
			\       'cterm': 'NONE', 
			\       'ctermfg': '252', 
			\       'ctermbg': '241' 
			\   }, 
			\   'stlLineInfo': { 
			\       'gui': 'NONE', 
			\       'font': 'NONE', 
			\       'guifg': '#9b9b9b', 
			\       'guibg': '#3c3c3c', 
			\       'cterm': 'NONE', 
			\       'ctermfg': '237',
			\       'ctermbg': '241' 
			\   }, 
			\   'stlTotal': { 
			\       'gui': 'NONE', 
			\       'font': 'NONE', 
			\       'guifg': '#9b9b9b', 
			\       'guibg': '#3c3c3c', 
			\       'cterm': 'NONE',
			\       'ctermfg': '237',
			\       'ctermbg': '241' 
			\   } 
			\ } 

if exists('*leaderf#colorscheme#mergePalette')
	let g:leaderf#colorscheme#lessthan#palette = leaderf#colorscheme#mergePalette(s:palette)
else
	let g:Lf_StlPalette = copy(s:palette)
endif
```

It only apply colors once and doesn't switch use palette from another colorscheme. Didn't know it is not supposed to be used from the colorscheme definitions.

**Comment by habamax** [comment]
@Yggdroot could you use `hi def` instead of `hi` for highlighting leaderf?

That way external ppl could overwrite your highlight groups from within colorschemes.

**Comment by habamax** [comment]
Just to recap.

Now it is possible to re remap all(?) highlight groups from within vim colorscheme:

![image](https://user-images.githubusercontent.com/234774/69491066-0c78fa80-0ea1-11ea-8a6a-753081db21c9.png)

![image](https://user-images.githubusercontent.com/234774/69491073-1bf84380-0ea1-11ea-93fb-d6e86034f781.png)

Although default gVim light colors are still not readable
![image](https://user-images.githubusercontent.com/234774/69491090-64176600-0ea1-11ea-9cf4-fcfd53562748.png)

The issue for me is solved. Thank you.

**Comment by Yggdroot** [comment]
Yes, you can remap all highlight groups.
Now the default light colorscheme is available.

**Comment by xulongwu4** [comment]
@habamax Can you tell me how you managed to fix the problem in this comment? https://github.com/Yggdroot/LeaderF/issues/402#issuecomment-556952128

**Comment by habamax** [comment]
Well, I don't remember :)

But currently I use following in my colorschemes:

https://github.com/habamax/vim-colors-defnoche/blob/542455a95f9dd4a3bf009a953cc707d19a0a8440/colors/defnoche.vim#L508

or 

https://github.com/habamax/.vim/blob/efd42d00e80d368432b5d4b8f3deb3c523a22bb7/colors/habamax.vim#L397

**Comment by albertnetymk** [comment]
Just my 2c: using `solarized8` light variant and `let g:Lf_PopupColorscheme = 'gruvbox_material'`, the cursor line is still not discernible, so I dropped `hi link Lf_hl_cursorline None` in my nvim config.

**Comment by jeremyjjbrown** [comment]
It would be really great if there was a complete explanation for how to just get existing theme colors in LeaderF. Maybe I am stupid but I am not piecing it together for myself and I need to be able to read the results to abandon NerdTree based workflows.

**Comment by Yggdroot** [comment]
> 
> 
> It would be really great if there was a complete explanation for how to just get existing theme colors in LeaderF. Maybe I am stupid but I am not piecing it together for myself and I need to be able to read the LeaderF results to abandon NerdTree based workflows.

All the highlight groups supported are defined in [LeaderF/autoload/leaderf/colorscheme/popup/default.vim](https://github.com/Yggdroot/LeaderF/blob/master/autoload/leaderf/colorscheme/popup/default.vim)

To change the colors of some highlight groups:
```vim
let g:Lf_PopupPalette = {
    \  'light': {
    \      'Lf_hl_match': {
    \                'gui': 'NONE',
    \                'font': 'NONE',
    \                'guifg': 'NONE',
    \                'guibg': '#303136',
    \                'cterm': 'NONE',
    \                'ctermfg': 'NONE',
    \                'ctermbg': '236'
    \              },
    \      'Lf_hl_cursorline': {
    \                'gui': 'NONE',
    \                'font': 'NONE',
    \                'guifg': 'NONE',
    \                'guibg': '#303136',
    \                'cterm': 'NONE',
    \                'ctermfg': 'NONE',
    \                'ctermbg': '236'
    \              },
    \      },
    \  'dark': {
    \         ...
    \         ...
    \      }
    \  }
```

**Comment by ApolloTang** [comment]
the above does seem to work. I have tried the following, no effect, is still yellow, bad contrast: 

```
let g:Lf_PopupPalette = {
    \  'light': {
    \      'Lf_hl_match': {
    \                'gui': 'NONE',
    \                'font': 'NONE',
    \                'guifg': '#000000', "<------
    \                'guibg': '#303136',
    \                'cterm': 'NONE',
    \                'ctermfg': 'NONE',
    \                'ctermbg': '236'
    \              },
    \      'Lf_hl_cursorline': {
    \                'gui': 'NONE',
    \                'font': 'NONE',
    \                'guifg': '#000000', "<-------
    \                'guibg': '#303136',
    \                'cterm': 'NONE',
    \                'ctermfg': 'NONE',
    \                'ctermbg': '236'
    \              },
    \      },
    \  }
```

<img width="589" alt="Screen Shot 2020-07-02 at 11 31 28 PM" src="https://user-images.githubusercontent.com/1150961/86429041-512d0580-bcbc-11ea-9123-1cfd53dfde15.png">

so I follow @albertnetymk advice: 
```
  "/ https://github.com/Yggdroot/LeaderF/issues/402#issuecomment-636458277
  hi link Lf_hl_cursorline None
```

**Comment by Yggdroot** [comment]
> the above does NOT seem to work. I have tried the following, no effect, is still yellow, bad contrast:
> 

are you using the latest version?
